<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Esti sigur ca doresti sa stergi acest articol?',
    'Create' => 'Adaugare',
    'Create Role Types' => 'Adaugare tipuri de roluri',
    'Delete' => 'Stergere',
    'Description' => 'Descriere',
    'ID' => 'ID',
    'Name' => 'Denumire',
    'Reset' => 'Resetare',
    'Role Types' => 'Tipuri de roluri',
    'Search' => 'Cautare',
    'Update' => 'Actualizare',
    'Update {modelClass}: ' => 'Actualizare {modelClass}: ',
    'Address' => 'Adresa',
    'Bank' => 'Banca',
    'CNP' => 'CNP',
    'CUI' => 'CUI',
    'City' => 'Localitate',
    'Contact Person' => 'Persoana de contact',
    'County' => 'Judet',
    'Firstname' => 'Prenume',
    'IBAN' => 'IBAN',
    'Lastname' => 'Nume',
    'Locale' => 'Local',
    'Phone' => 'Telefon',
    'Picture' => 'Imagine',
    'Postal Code' => 'Cod postal',
    'Status' => 'Status',
    'Type' => 'Tip',
    'Abonat' => 'Abonat',
    'Active' => 'Activ',
    'Add' => 'Adaugare',
    'Admin' => 'Admin',
    'Client type' => 'Tip client',
    'Inactive' => 'Inactiv',
    'Neabonat' => 'Neabonat',
    'Newsletter' => 'Newsletter',
    'Orders' => 'Comenzi',
    'Tools' => 'Ustensile',
    'Users' => 'Utilizatori',
];
